Repository McFrappe/TTT, pull requests merged in 2021-01, with the labels that each got.

#1 created Astyle formatting bot that will format code for us.
  .github/workflows/main.yml
Labels: enhancement

#6 wrote test program for ncurses
  makefile
  src/main.c
  src/ui.c
  src/ui.h
Labels: documentation, enhancement

#10 API requests now work properly to our expectations
  .github/workflows/main.yml
  makefile
  src/api.c
  src/api.h
  src/json_response.c
  src/json_response.h
  src/main.c
  src/parser.c
  src/parser.h
  src/ui.h
Labels: implementation

#15 Add parser for JSON response
  .gitignore
  makefile
  src/api.c
  src/api.h
  src/main.c
  src/pages.c
  src/pages.h
  src/parser.c
  src/parser.h
Labels: implementation

#17 feat: add cunit tests for parser
  README.md
  makefile
  src/parser.c
  src/parser.h
  test/data/index.json
  test/data/range.json
  test/unittests.c
Labels: testing

#18 fix: update parser to pass tests
  .github/workflows/C-runTests.yml
  .github/workflows/tests.yml
  makefile
  src/api.c
  src/pages.c
  src/pages.h
  src/parser.c
  test/data/range_large.json
  test/unittests.c
Labels: implementation
